WW:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/WWTo2L2Nu_NNPDF31_TuneCP5_13TeV-powheg-pythia8.root
  type:
    background
  kfactor: 1.0
  color: 842

VVV:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/WZZ_TuneCP5_13TeV-amcatnlo-pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/WWZ_TuneCP5_13TeV-amcatnlo-pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/ZZZ_TuneCP5_13TeV-amcatnlo-pythia8.root
  type:
    background
  color: 895

ZZ:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8.root
    #- eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/ZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/ZZTo4L_TuneCP5_13TeV_powheg_pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/GluGluToContinToZZTo2e2mu_13TeV_MCFM701_pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/GluGluToContinToZZTo2e2nu_13TeV_MCFM701_pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/GluGluToContinToZZTo2e2tau_13TeV_MCFM701_pythia8.root
    #- /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/GluGluToContinToZZTo2mu2nu_13TeV_MCFM701_pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/GluGluToContinToZZTo2mu2tau_13TeV_MCFM701_pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/GluGluToContinToZZTo4e_13TeV_MCFM701_pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/GluGluToContinToZZTo4mu_13TeV_MCFM701_pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/GluGluToContinToZZTo4tau_13TeV_MCFM701_pythia8.root
  type:
    background
  color: 798

WZ:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8.root
#    - eos/WZTo2L2Q
  type:
    background
  kfactor: 1.0
  color: 856

DY:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/DY1JetsToLL_M-50_LHEZpT_50-150_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/DY1JetsToLL_M-50_LHEZpT_150-250_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/DY1JetsToLL_M-50_LHEZpT_250-400_TuneCP5_13TeV-amcnloFXFX-pythia8.root
   # - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/DY1JetsToLL_M-50_LHEZpT_400-inf_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/DY2JetsToLL_M-50_LHEZpT_50-150_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/DY2JetsToLL_M-50_LHEZpT_150-250_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/DY2JetsToLL_M-50_LHEZpT_250-400_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/DY2JetsToLL_M-50_LHEZpT_400-inf_TuneCP5_13TeV-amcnloFXFX-pythia8.root
  type:
    background
  color: 901
  kfactor: 1.0

TOP:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/TTWJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/TTWJetsToQQ_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/TTZToQQ_TuneCP5_13TeV-amcatnlo-pythia8.root
  type:
    background
  color: 124
  kfactor: 1.0
Data:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/DoubleMuon_Run2018A-Nano1June2019-v1.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/DoubleMuon_Run2018B-Nano1June2019-v1.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/DoubleMuon_Run2018C-Nano1June2019-v1.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/DoubleMuon_Run2018D-Nano1June2019_ver2-v1.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/MuonEG_Run2018A-Nano1June2019-v1.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/MuonEG_Run2018B-Nano1June2019-v1.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/MuonEG_Run2018C-Nano1June2019-v1.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/MuonEG_Run2018D-Nano1June2019_ver2-v1.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/EGamma_Run2018A-Nano1June2019-v1.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/EGamma_Run2018B-Nano1June2019-v1.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/EGamma_Run2018C-Nano1June2019-v1.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/EGamma_Run2018D-Nano1June2019-v1.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/SingleMuon_Run2018A-Nano1June2019-v1.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/SingleMuon_Run2018B-Nano1June2019-v1.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/SingleMuon_Run2018C-Nano1June2019-v1.root
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/SingleMuon_Run2018D-Nano1June2019-v1.root
  type:
    data
  color: 1

DM:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/LionKing2018/merged2018/DMSimp_MonoZLL_Pseudo_TuneCP5_GQ1p0_GDM1p0_MY0-1000_mxd-1.root 
  type:
    signal
  color:
    2
