WW:
  files:
    - data/WWTo2L2Nu_NNPDF31_TuneCP5_PSweights_13TeV-powheg-pythia8.root
  type: background
  color: 842
  
VVV:
  files:
    - data/WWZ_4F_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/WZZ_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/ZZZ_TuneCP5_13TeV-amcatnlo-pythia8.root
  type: background
  color: 895

Other:
  files:
    - data/DYJetsToTauTau_ForcedMuEleDecay_M-50_TuneCP5_PSweights_13TeV-amcatnloFXFX-pythia8.root
  type:
    background
  color: 55

ZZ:
  files:
    - data/ZZTo2L2Nu_13TeV_powheg_pythia8.root
    - data/ZZTo4L_13TeV_powheg_pythia8.root
    - data/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
    - data/GluGluToContinToZZTo2e2mu_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo2e2nu_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo2e2tau_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo2mu2nu_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo2mu2tau_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo4e_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo4mu_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo4tau_13TeV_MCFM701_pythia8.root
  type:
    background
  color: 798

WZ:
  files:
    - data/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
    - data/WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8.root
  type:
    background
  kfactor: 1.0
  color: 856

DY:
  files:
    - data/DY1JetsToLL_M-50_LHEZpT_50-150_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY1JetsToLL_M-50_LHEZpT_150-250_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY1JetsToLL_M-50_LHEZpT_250-400_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY1JetsToLL_M-50_LHEZpT_400-inf_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_50-150_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_150-250_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_250-400_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_400-inf_TuneCP5_13TeV-amcnloFXFX-pythia8.root
  type:
    background
  color: 901

TOP:
  files:
    - data/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8.root
    - data/ST_tW_top_5f_inclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8.root
    - data/TTTo2L2Nu_TuneCP5_PSweights_13TeV-powheg-pythia8.root
    - data/TTWJetsToLNu_TuneCP5_PSweights_13TeV-amcatnloFXFX-madspin-pythia8.root
    - data/TTZToLLNuNu_M-10_TuneCP5_PSweights_13TeV-amcatnlo-pythia8.root
    - data/TTWJetsToQQ_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root
    - data/TTZToQQ_TuneCP5_13TeV-amcatnlo-pythia8.root
  type:
    background
  color: 124
  kfactor: 2.16

Data:
  files:
    - data/DoubleEG_Run2017B-Nano1June2019-v1.root
    - data/DoubleEG_Run2017C-Nano1June2019-v1.root
    - data/DoubleEG_Run2017D-Nano1June2019-v1.root
    - data/DoubleEG_Run2017E-Nano1June2019-v1.root
    - data/DoubleEG_Run2017F-Nano1June2019-v1.root
    - data/DoubleMuon_Run2017B-Nano1June2019-v1.root
    - data/DoubleMuon_Run2017C-Nano1June2019-v1.root
    - data/DoubleMuon_Run2017D-Nano1June2019-v1.root
    - data/DoubleMuon_Run2017E-Nano1June2019-v1.root
    - data/DoubleMuon_Run2017F-Nano1June2019-v1.root
    - data/MuonEG_Run2017B-Nano1June2019-v1.root
    - data/MuonEG_Run2017C-Nano1June2019-v1.root
    - data/MuonEG_Run2017D-Nano1June2019-v1.root
    - data/MuonEG_Run2017E-Nano1June2019-v1.root
    - data/MuonEG_Run2017F-Nano1June2019-v1.root
    - data/SingleElectron_Run2017B-Nano1June2019-v1.root
    - data/SingleElectron_Run2017C-Nano1June2019-v1.root
    - data/SingleElectron_Run2017D-Nano1June2019-v1.root
    - data/SingleElectron_Run2017E-Nano1June2019-v1.root
    - data/SingleElectron_Run2017F-Nano1June2019-v1.root
    - data/SingleMuon_Run2017B-Nano1June2019-v1.root
    - data/SingleMuon_Run2017C-Nano1June2019-v1.root
    - data/SingleMuon_Run2017D-Nano1June2019-v1.root
    - data/SingleMuon_Run2017E-Nano1June2019-v1.root
    - data/SingleMuon_Run2017F-Nano1June2019-v1.root
  type:
    data
  color: 1

#ADDMonoZ_MD_1_d_2:
#  files:
#    - data/ADDMonoZ2017_MD_1_d_2.root
#  type:
#    signal
#  color:
#    2
